version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000" # Backend (Express server)
      - "3002:3002" # BrowserSync
    volumes:
      - .:/app                  # Sync host files with container
      - /app/node_modules       # Prevent overwriting node_modules
    command: sh -c "npm run dev & npm run sync" # Run both nodemon and BrowserSync - !!!!ADDED!!!!
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
